#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032_quanser
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Quanser Project.
# Description:       Configures GPIO for Quanser Project.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "GalileoGen2")
				############################################################################################
				# IO3 input - ELB1
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio16 ] ; then
					echo -n "16" > /sys/class/gpio/export
				fi
				echo -n "in" > /sys/class/gpio/gpio16/direction
				echo -n "0" > /sys/class/gpio/gpio16/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio17 ] ; then
					echo -n "17" > /sys/class/gpio/export
				fi

				### No pull-up neither pull-down
				echo -n "in" > /sys/class/gpio/gpio17/direction

				## Pin Mux 1 GPIO
				if [ ! -d /sys/class/gpio/gpio76 ] ; then
					echo -n "76" > /sys/class/gpio/export
				fi

				echo -n "in" > /sys/class/gpio/gpio76/direction
				echo -n "0" > /sys/class/gpio/gpio76/value

				## Pin Mux 2 GPIO
				if [ ! -d /sys/class/gpio/gpio64 ] ; then
					echo -n "64" > /sys/class/gpio/export
				fi

				echo -n "in" > /sys/class/gpio/gpio64/direction
				echo -n "0" > /sys/class/gpio/gpio64/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio14 ] ; then
					echo -n "14" > /sys/class/gpio/export
				fi

				echo -n "in" > /sys/class/gpio/gpio14/direction
				## Permissions
				chgrp gpio /sys/class/gpio/gpio14/value
				chmod g+rw /sys/class/gpio/gpio14/value

				############################################################################################
				# IO2 input - ELB2
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio34 ] ; then
					echo -n "34" > /sys/class/gpio/export
				fi
				echo -n "in" > /sys/class/gpio/gpio34/direction
				echo -n "0" > /sys/class/gpio/gpio34/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio35 ] ; then
					echo -n "35" > /sys/class/gpio/export
				fi

				### No pull-up neither pull-down
				echo -n "in" > /sys/class/gpio/gpio35/direction

				## Pin Mux 1 GPIO
				if [ ! -d /sys/class/gpio/gpio77 ] ; then
					echo -n "77" > /sys/class/gpio/export
				fi

				echo -n "in" > /sys/class/gpio/gpio77/direction
				echo -n "0" > /sys/class/gpio/gpio77/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio13 ] ; then
					echo -n "13" > /sys/class/gpio/export
				fi

				echo -n "in" > /sys/class/gpio/gpio13/direction
				## Permissions
				chgrp gpio /sys/class/gpio/gpio13/value
				chmod g+rw /sys/class/gpio/gpio13/value
				
				############################################################################################
				# IO5 PWM3 - PWM
				
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio18 ] ; then
					echo -n "18" > /sys/class/gpio/export
				fi

				echo -n "out" > /sys/class/gpio/gpio18/direction
				echo -n "0" > /sys/class/gpio/gpio18/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio19 ] ; then
					echo -n "19" > /sys/class/gpio/export
				fi

				### No pull up or pull down
				echo -n "in" > /sys/class/gpio/gpio19/direction

				# Pin Mux 1 GPIO  
				if [ ! -d /sys/class/gpio/gpio66 ] ; then
					echo -n "66" > /sys/class/gpio/export
				fi
				echo -n "1" > /sys/class/gpio/gpio66/value

				# PWM3 configuration - Linux
				if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
					echo -n "3" > /sys/class/pwm/pwmchip0/export
				fi

				## Permissions
				chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
				chmod g+rw /sys/class/pwm/pwmchip0/device/pwm_period
				chgrp pwm /sys/class/pwm/pwmchip0/pwm3/duty_cycle
				chmod g+rw /sys/class/pwm/pwmchip0/pwm3/duty_cycle
				chgrp pwm /sys/class/pwm/pwmchip0/pwm3/enable
				chmod g+rw /sys/class/pwm/pwmchip0/pwm3/enable

				############################################################################################
				# CONFIGURE SPI IOs
				#
				# Configures IO10 for SPI #SS
				#	gpio26=0 (output)
				#	gpio27=1 (pull-up)
				#	gpio74=0 (IO10 is GPIO)
				if [ ! -d /sys/class/gpio/gpio26 ] ; then
					echo -n "26" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio26/direction
				echo -n "0" > /sys/class/gpio/gpio26/value
				
				if [ ! -d /sys/class/gpio/gpio27 ] ; then
					echo -n "27" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio27/direction
				echo -n "1" > /sys/class/gpio/gpio27/value
				
				if [ ! -d /sys/class/gpio/gpio74 ] ; then
					echo -n "74" > /sys/class/gpio/export
				fi
				echo -n "0" > /sys/class/gpio/gpio74/value
				
				# Configures IO11 for SPI MOSI
				#	gpio24=0 (output)
				#	gpio25=input (floating)
				#	gpio44=1 (IO11 is SPI)
				#	gpio72=0 (IO11 is SPI)
				if [ ! -d /sys/class/gpio/gpio24 ] ; then
					echo -n "24" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio24/direction
				echo -n "0" > /sys/class/gpio/gpio24/value
				
				if [ ! -d /sys/class/gpio/gpio25 ] ; then
					echo -n "25" > /sys/class/gpio/export
				fi
				echo -n "in" > /sys/class/gpio/gpio25/direction
				
				if [ ! -d /sys/class/gpio/gpio44 ] ; then
					echo -n "44" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio44/direction
				echo -n "1" > /sys/class/gpio/gpio44/value
				
				if [ ! -d /sys/class/gpio/gpio72 ] ; then
					echo -n "72" > /sys/class/gpio/export
				fi
				echo -n "0" > /sys/class/gpio/gpio72/value

				# Configures IO12 for SPI MISO
				#	gpio42=1 (input)
				#	gpio43=input (floating)
				if [ ! -d /sys/class/gpio/gpio42 ] ; then
					echo -n "42" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio42/direction
				echo -n "1" > /sys/class/gpio/gpio42/value
				
				if [ ! -d /sys/class/gpio/gpio43 ] ; then
					echo -n "43" > /sys/class/gpio/export
				fi
				echo -n "in" > /sys/class/gpio/gpio43/direction

				# Configure IO13 for SPI SCLK
				#	gpio30=0 (output)
				#	gpio31=0 (pull-down, SCLK mode 0)
				#	gpio46=1 (IO13 is SPI)
				if [ ! -d /sys/class/gpio/gpio30 ] ; then
					echo -n "30" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio30/direction
				echo -n "0" > /sys/class/gpio/gpio30/value
				
				if [ ! -d /sys/class/gpio/gpio31 ] ; then
					echo -n "31" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio31/direction
				echo -n "0" > /sys/class/gpio/gpio31/value
				
				if [ ! -d /sys/class/gpio/gpio46 ] ; then
					echo -n "46" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio46/direction
				echo -n "1" > /sys/class/gpio/gpio46/value

				############################################################################################
				# IO4 output - ENABLE
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio36 ] ; then
					echo -n "36" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio36/direction
				echo -n "0" > /sys/class/gpio/gpio36/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio37 ] ; then
					echo -n "37" > /sys/class/gpio/export
				fi

				### Pull-up
				echo -n "out" > /sys/class/gpio/gpio37/direction
				echo -n "1" > /sys/class/gpio/gpio37/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio6 ] ; then
					echo -n "6" > /sys/class/gpio/export
				fi

				## Permissions
				chgrp gpio /sys/class/gpio/gpio6/value
				chmod g+rw /sys/class/gpio/gpio6/value

				############################################################################################
				# A0 - AD
				## Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio49 ] ; then
					echo -n "49" > /sys/class/gpio/export
				fi
				### No pull-up neither pull-down
				echo -n "in" > /sys/class/gpio/gpio49/direction

				## ADC AO configuration
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale

				############################################################################################
				# A1 - ATH_FLAG
				## Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio51 ] ; then
					echo -n "51" > /sys/class/gpio/export
				fi
				### No pull-up neither pull-down
				echo -n "in" > /sys/class/gpio/gpio51/direction

				## ADC AO configuration
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage1_raw
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage1_raw
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage1_scale
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage1_scale
	;;
    esac
		chgrp spi /dev/spidev1.0
		chmod g+rw /dev/spidev1.0
    ;;
  stop)
    case $boardId in
      "GalileoGen2")
				# IO3 input - ELB1
				echo -n "in" > /sys/class/gpio/gpio16/direction
				echo -n "1" > /sys/class/gpio/gpio16/value
				echo -n "16" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio17/direction
				echo -n "1" > /sys/class/gpio/gpio17/value
				echo -n "17" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio76/direction
				echo -n "1" > /sys/class/gpio/gpio76/value
				echo -n "76" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio64/direction
				echo -n "1" > /sys/class/gpio/gpio64/value
				echo -n "64" > /sys/class/gpio/unexport
				echo -n "14" > /sys/class/gpio/unexport
				# IO2 input - ELB2
				echo -n "in" > /sys/class/gpio/gpio34/direction
				echo -n "1" > /sys/class/gpio/gpio34/value
				echo -n "34" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio35/direction
				echo -n "1" > /sys/class/gpio/gpio35/value
				echo -n "35" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio77/direction
				echo -n "1" > /sys/class/gpio/gpio77/value
				echo -n "77" > /sys/class/gpio/unexport
				echo -n "13" > /sys/class/gpio/unexport
				# PWM 3
				echo -n "in" > /sys/class/gpio/gpio18/direction
				echo -n "1" > /sys/class/gpio/gpio18/value
				echo -n "18" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio19/direction
				echo -n "1" > /sys/class/gpio/gpio19/value
				echo -n "19" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio66/direction
				echo -n "1" > /sys/class/gpio/gpio66/value
				echo -n "66" > /sys/class/gpio/unexport
				echo -n "0" > /sys/class/pwm/pwmchip0/pwm3/enable
				echo -n "3" > /sys/class/pwm/pwmchip0/unexport
				# SPI
				echo -n "1" > /sys/class/gpio/gpio26/value
				echo -n "26" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio27/direction
				echo -n "74" > /sys/class/gpio/unexport
				echo -n "1" > /sys/class/gpio/gpio24/value
				echo -n "24" > /sys/class/gpio/unexport
				echo -n "25" > /sys/class/gpio/unexport
				echo -n "0" > /sys/class/gpio/gpio44/value
				echo -n "44" > /sys/class/gpio/unexport
				echo -n "72" > /sys/class/gpio/unexport
				echo -n "42" > /sys/class/gpio/unexport
				echo -n "43" > /sys/class/gpio/unexport
				echo -n "0" > /sys/class/gpio/gpio46/value
				echo -n "46" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio31/direction
				echo -n "31" > /sys/class/gpio/unexport
				echo -n "1" > /sys/class/gpio/gpio30/value
				echo -n "30" > /sys/class/gpio/unexport
				# ENABLE
				echo -n "in" > /sys/class/gpio/gpio36/direction
				echo -n "1" > /sys/class/gpio/gpio36/value
				echo -n "36" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio37/direction
				echo -n "1" > /sys/class/gpio/gpio37/value
				echo -n "37" > /sys/class/gpio/unexport
				echo -n "6" > /sys/class/gpio/unexport				
	;;
    esac
    ;;
  status)
    	ls -d /sys/class/gpio/gpio*
	;;
  *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
