#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032_quanser
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Quanser Project.
# Description:       Configures GPIO for Quanser Project.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "GalileoGen2")
				############################################################################################
				# IO3 output - ELB1 
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio16 ] ; then
					echo -n "16" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio16/direction
				echo -n "0" > /sys/class/gpio/gpio16/value

				## Pin Mux 1 GPIO
				if [ ! -d /sys/class/gpio/gpio76 ] ; then
					echo -n "76" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio76/direction
				echo -n "0" > /sys/class/gpio/gpio76/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio14 ] ; then
					echo -n "14" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio14/direction

				## Permissions
				chgrp gpio /sys/class/gpio/gpio14/value
				chmod g+rw /sys/class/gpio/gpio14/value

				############################################################################################
				# IO2 output - ELB2 
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio34 ] ; then
					echo -n "34" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio34/direction
				echo -n "0" > /sys/class/gpio/gpio34/value

				## Pin Mux 1 GPIO
				if [ ! -d /sys/class/gpio/gpio77 ] ; then
					echo -n "77" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio77/direction
				echo -n "0" > /sys/class/gpio/gpio77/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio13 ] ; then
					echo -n "13" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio13/direction

				## Permissions
				chgrp gpio /sys/class/gpio/gpio13/value
				chmod g+rw /sys/class/gpio/gpio13/value

	;;
    esac
    ;;
  stop)
    case $boardId in
      "GalileoGen2")
				# IO3 output - ELB1
				echo -n "1" > /sys/class/gpio/gpio16/value
				echo -n "16" > /sys/class/gpio/unexport
				echo -n "76" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio14/direction
				echo -n "14" > /sys/class/gpio/unexport
				# IO2 output - ELB2
				echo -n "1" > /sys/class/gpio/gpio34/value
				echo -n "34" > /sys/class/gpio/unexport
				echo -n "77" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio13/direction
				echo -n "13" > /sys/class/gpio/unexport
	;;
    esac
    ;;
  status)
    	ls -d /sys/class/gpio/gpio*
	;;
  *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
